[build]
  command = """
    python -m pip install --upgrade pip &&
    pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu &&
    streamlit run main.py --server.port=$PORT --server.headless=true
  """
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.10"
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
