[build]
- command = "pip install -r requirements.txt && streamlit run main.py --server.port=$PORT"
+ command = "pip install -r requirements.txt --extra-index-url=https://download.pytorch.org/whl/cpu && streamlit run main.py --server.port=$PORT"
