[build]
  command = "pip install -r requirements.txt && streamlit run main.py --server.port=$PORT --server.headless=true"
  publish = "."
[build.environment]
  PYTHON_VERSION = "3.10"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
