[build]
  command = """
    pip install --upgrade pip && 
    pip install -r requirements.txt && 
    streamlit run main.py
  """
  publish = "."
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.10"
  STREAMLIT_SERVER_HEADLESS = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/app/*"
  to = "/"
  status = 200
