[build]
  command = "pip install -r requirements.txt --extra-index-url=https://download.pytorch.org/whl/cpu && streamlit run main.py --server.port=${PORT:-8501}"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
