[build]
  command = "pip install -r requirements.txt && streamlit run main.py"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[build.environment]
  NODE_VERSION = "16"  # シェル環境を強制するために必要
